// Generated by npm run build. Regenerate after changing content or assets.
const CACHE='umbral-'+new URL(self.registration.scope).pathname+'-f44d95fce232ecf1';
const PREFIX='umbral-'+new URL(self.registration.scope).pathname+'-';
const ASSETS=["./","./index.html","./app.js","./app.css","./library.css","./data.json","./manifest.webmanifest","./icon.svg","./icon-192.png","./icon-512.png"];
self.addEventListener('install',event=>{
  if (typeof self.skipWaiting === 'function') self.skipWaiting();
  event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));
});
self.addEventListener('activate',event=>event.waitUntil((async()=>{
  for(const name of await caches.keys()) if(name.startsWith(PREFIX)&&name!==CACHE) await caches.delete(name);
  await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
  const url=new URL(event.request.url);
  if(event.request.method!=='GET'||!url.href.startsWith(self.registration.scope)) return;
  event.respondWith((async()=>{
    const cache=await caches.open(CACHE);
    const cached=await cache.match(event.request,{ignoreSearch:true});
    if(cached) return cached;
    try { return await fetch(event.request); }
    catch(error) { if(event.request.mode==='navigate') return await cache.match('./index.html'); throw error; }
  })());
});
