import fs from 'node:fs';
import { createHash } from 'node:crypto';
const assets=['./','./index.html','./app.js','./app.css','./library.css','./data.json','./manifest.webmanifest','./icon.svg','./icon-192.png','./icon-512.png'];
const hash=createHash('sha256');
for(const file of assets.slice(1)) hash.update(fs.readFileSync(file));
const revision=hash.digest('hex').slice(0,16);
const worker=`// Generated by npm run build. Regenerate after changing content or assets.
const CACHE='umbral-'+new URL(self.registration.scope).pathname+'-${revision}';
const PREFIX='umbral-'+new URL(self.registration.scope).pathname+'-';
const ASSETS=${JSON.stringify(assets)};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
  for(const name of await caches.keys()) if(name.startsWith(PREFIX)&&name!==CACHE) await caches.delete(name);
  await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
  const url=new URL(event.request.url);
  if(event.request.method!=='GET'||!url.href.startsWith(self.registration.scope)) return;
  event.respondWith((async()=>{
    const cache=await caches.open(CACHE);
    const cached=await cache.match(event.request,{ignoreSearch:true});
    if(cached) return cached;
    try { return await fetch(event.request); }
    catch(error) { if(event.request.mode==='navigate') return await cache.match('./index.html'); throw error; }
  })());
});
`;
fs.writeFileSync('sw.js',worker);
console.log('Sitio estático preparado. Versión offline: '+revision);
